In [2]:
import numpy as np
from ovito.data import DataCollection, NearestNeighborFinder
from ovito.io import import_file

conf_fn = "fcc.dump"
pipeline = import_file(conf_fn)

data = pipeline.compute()

/home/yangsl/src/miniconda3/envs/tmp/lib/python3.11/site-packages/ovito/_extensions/anari.py:2: UserWarning: Did you accidentally install the OVITO package from the PyPI repository in an Anaconda/Miniconda Python interpreter using the 'pip' command? This will likely lead to conflicts with existing libraries in the Anaconda environment, and import of the OVITO module may fail with an error related to the Qt framework. To fix this, please uninstall the ovito pip package by running 'pip uninstall -y ovito PySide6' and then install the OVITO Anaconda package provided by OVITO GmbH. Visit https://docs.ovito.org/python/introduction/installation.html for further instructions. If you would rather like to ignore this warning message, add the following code to the top of your Python script:

  import warnings
  warnings.filterwarnings('ignore', message='.*OVITO.*PyPI')

  import ovito._extensions.pyscript


In [3]:
data.attributes

{'SourceFrame': 0, 'SourceFile': '/home/yangsl/scripts/WarrenCowleyParameters/examples/fcc.dump', 'Timestep': 0}

In [4]:
natoms = data.particles.count
natoms

4000

In [7]:
particle_types = np.array(data.particles.particle_type)
# particle_types = np.array(data.particles.particle_types)
particle_types

array([1, 3, 2, ..., 1, 3, 2], dtype=int32)

In [13]:
unique_types, counts = np.unique(particle_types, return_counts=True)
concentrations = counts / natoms
print(unique_types, counts, concentrations)

[1 2 3] [1334 1333 1333] [0.3335  0.33325 0.33325]


In [16]:
finder = NearestNeighborFinder(N=1, data_collection=data)
neighbor_indices, _ = finder.find_all()
print(neighbor_indices)
print(_)

[[   1]
 [   0]
 [   0]
 ...
 [3999]
 [3999]
 [3998]]
[[[ 1.76792  1.76792  0.     ]]

 [[-1.76792 -1.76792  0.     ]]

 [[-1.76792  0.      -1.76792]]

 ...

 [[-1.7679   0.       1.7679 ]]

 [[-1.7679   1.7679   0.     ]]

 [[ 1.7679  -1.7679   0.     ]]]
